CREATE TABLE pl_matches_hist AS 
WITH summed AS (
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2000'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2001'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2002'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2003'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2004'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2005'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2006'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2007'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2008'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2009'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2010'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2011'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2012'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2013'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2014'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2015'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2016'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR 	
FROM '2017')
SELECT Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,"AS",HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
FROM summed
;


 
 
  
  
  
 
 
 
 
  
  
  
  
  
  
  
  