CREATE TABLE ENG_match_odds AS 
WITH summed AS (
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2000'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2001'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2002'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2003'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2004'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2005'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2006'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2007'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2008'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2009'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2010'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2011'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2012'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2013'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2014'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2015'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2016'
UNION
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA 	
FROM '2017')
SELECT Div,Date,HomeTeam,AwayTeam,IWH,IWD,IWA,LBH,LBD,LBA,WHH,WHD,WHA
FROM summed
;


 
 
  
  
  
 
 
 
 
  
  
  
  
  
  
  
  